server:
  port: 9070
  http2:
    enabled: true
  ssl:
    enabled: true
    key-store: server.p12
    key-store-password: 1234
    key-store-type: PKCS12
    key-alias: bns-ssl

spring:
  application:
    name: apiGateway
