server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service
          predicates:
            - Path=/api/auth/**

        - id: user-service
          uri: http://user-service
          predicates:
            - Path=/api/users/**

        - id: order-service
          uri: http://order-service
          predicates:
            - Path=/api/orders/**

        - id: product-service-products
          uri: http://product-service
          predicates:
            - Path=/api/products/**

        - id: product-service-stores
          uri: http://product-service
          predicates:
            - Path=/api/stores/**

        - id: seller-service
          uri: http://seller-service
          predicates:
            - Path=/api/sellers/**

        - id: pay-service
          uri: http://pay-service
          predicates:
            - Path=/api/pay/**
