server:
  port: 9070
  http2:
    enabled: true
  ssl:
    enabled: true
    key-store: server.p12
    key-store-password: 1234
    key-store-type: PKCS12
    key-alias: bns-ssl

spring:
  application:
    name: apiGateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 10000

jwt:
  secret: 552925bb-fddf-4b48-8d9f-fe902dcf12fd

