server:
  port: 9070
  http2:
    enabled: true
  ssl:
    enabled: true
    key-store: server.p12
    key-store-password: 1234
    key-store-type: PKCS12
    key-alias: bns-ssl

spring:
  application:
    name: apiGateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:9060
          predicates:
            - Path=/api/auth/**

        - id: user-service
          uri: http://localhost:9030
          predicates:
            - Path=/api/users/**

        - id: order-service
          uri: http://localhost:9040
          predicates:
            - Path=/api/orders/**

        - id: product-service-products
          uri: http://localhost:9090
          predicates:
            - Path=/api/products/**

        - id: product-service-stores
          uri: http://localhost:9090
          predicates:
            - Path=/api/stores/**

        - id: seller-service
          uri: http://localhost:9020
          predicates:
            - Path=/api/sellers/**

        - id: pay-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/pay/**

      httpclient:
        connect-timeout: 5000
        response-timeout: 10000

jwt:
  secret: 552925bb-fddf-4b48-8d9f-fe902dcf12fd

