apiVersion: apps/v1
kind: Deployment
metadata:
  name: payservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payservice
  template:
    metadata:
      labels:
        app: payservice
    spec:
      containers:
        - name: payservice
          image: lass9436/payservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
