server:
  port: 9020
  http2:
    enabled: true
  ssl:
    enabled: true
    key-store: server.p12
    key-store-password: 1234
    key-store-type: PKCS12
    key-alias: bns-ssl

spring:
  application:
    name: sellerService
  jpa:
    open-in-view: false
  cloud:
    openfeign:
      okhttp:
        enabled: true
      http2client:
        enabled: true

product:
  service:
    url: https://localhost:9010

user:
  service:
    url: https://localhost:9030

