server:
  port: 9020

spring:
  application:
    name: sellerService
  jpa:
    open-in-view: false
  cloud:
    openfeign:
      okhttp:
        enabled: true
      http2client:
        enabled: true

api:
  gateway:
    url: https://localhost:9070

