server:
  port: 9040
  http2:
    enabled: true
  ssl:
    enabled: true
    key-store: server.p12
    key-store-password: 1234
    key-store-type: PKCS12
    key-alias: bns-ssl

spring:
  application:
    name: orderService
  jpa:
    open-in-view: false
  cloud:
    openfeign:
      okhttp:
        enabled: true
      http2client:
        enabled: true

seller:
  service:
    url: http://localhost:9020

product:
  service:
    url: https://localhost:9010

user:
  service:
    url: http://localhost:9030

logging:
  level:
    com.example.client.ProductClient: DEBUG
    feign.Logger: DEBUG
    feign.Request: DEBUG
    feign.Response: DEBUG
