# Replica 설정
replicaCount: 3               # 배포할 Pod 수 (예: 3개)

namespace: msa

# 컨테이너 이미지 설정
image:
  user: lass9436   # 컨테이너 이미지 경로
  tag: latest                 # 컨테이너 이미지 태그
  pullPolicy: Always    # 이미지 Pull 정책 (IfNotPresent, Always 등)

# 서비스 설정
service:
  port: 80                    # 클라이언트가 접근하는 Service Port
  targetPort: 8080            # 내부 Pod에서 포워딩되는 Container Port
  type: LoadBalancer          # Kubernetes 서비스 타입 (LoadBalancer, ClusterIP, NodePort)

# 환경 변수 (ConfigMap 연동)
env:
  environment: prod           # 환경 (dev, staging, prod 등)

# 로그 및 기타 설정
logging:
  level: INFO                 # 기본 로깅 레벨 (DEBUG, INFO, WARN, ERROR 등)
