# Replica 설정
replicaCount: 1               # 배포할 Pod 수 (예: 3개)

namespace: msa

# 컨테이너 이미지 설정
image:
  user: lass9436   # 컨테이너 이미지 경로
  tag: latest                 # 컨테이너 이미지 태그
  pullPolicy: Always    # 이미지 Pull 정책 (IfNotPresent, Always 등)

# 서비스 설정
# values.yaml
defaultService:
  type: ClusterIP   # 기본 서비스 타입
  port: 80          # Default 서비스 포트
  targetPort: 8080  # 기본적으로 포워딩할 컨테이너 포트

apigateway:
  type: LoadBalancer

# 환경 변수 (ConfigMap 연동)
env:
  environment: prod           # 환경 (dev, staging, prod 등)

# 로그 및 기타 설정
logging:
  level: INFO                 # 기본 로깅 레벨 (DEBUG, INFO, WARN, ERROR 등)
